### ISSUE TITLE
built own mask

### ISSUE THREAD

**Issue by dlpy19** [edosedgar/mtcnnattack#1]
Hi Dear,
thank you for sharing your work,
I tested ur code and  is working fine, however I could not figure out how to set my own mask on my photo.
I would be grateful if you explain  the steps.
Regards

**Comment by edosedgar** [comment]
Hello,

it is said in README.md, that you need to take photos with a checkerboard on the places you want to apply patches, then manually mark the crosses of checkerboard (with a desired accuracy, not necessarily you need to take all of them)
Each row should be same-colored, for example (255,0,0)
The next row of the same mask will be (254, 0, 0) and do it in the same fashion till the end of rows within a mask
On the next mask you pick another color, let's take (0,255,0) and follow the guideline above

In a code, you should create masks with a given resolution and pass the initial color and gradient (difference between neighboring markers on a checkerboard)

**Comment by SURABHI-GUPTA** [comment]
@edosedgar @dlpy19 I still didn't get what is the need of checkerboard.
