### ISSUE TITLE
What is the reason for the checkerboard?

### ISSUE THREAD

**Issue by ShaharHoory** [edosedgar/mtcnnattack#2]
Hello
First, thank you for that wonderful contribution.
1) What is this checkerboard for?
Why did you use it instead of just marking the 8 points straight on the face? (with no checkerboard at all).
2) Does your code generate a mask on the checkerboard's place, or uses it as a physical mask? (in order to apply the patch addition on the image).
Thank you!

**Comment by edosedgar** [comment]
Hello, welcome, share and enjoy :)
First of all, I would recommend you to look for the previous issue where I provided a detailed explanation on most of the questions you asked.

1. Checkerboard is used to indicate the grid perspective in a way it happens in the real life
2. The code uses only color markers, the checkerboard itself is not required to apply the masks, points are added over the checkerboard. Anyway, areas with checkerboard will be covered with the masks.
