### ISSUE TITLE
How to set the mask array

### ISSUE THREAD

**Issue by zhjikoshlizhzc** [edosedgar/mtcnnattack#4]
Hello.
I've changed the input photo with my own photo with two checkerboard squares on my face. 
Then when I run `adversarial_pen.py`,there is a error:
`
  File ".\mtcnnattack-master\utils\patch_mng.py", line 124, in init_src_parts
    x = np.linspace(0, self.mask_np.shape[1], self.grid_size[1]).astype(np.int32)

TypeError: 'NoneType' object is not subscriptable`

If the reason is that I didn't set masks = {
'left_cheek: [np zeros ((150, 180, 1)), (0, 255, 0), (0, 1, 0)].
'right_cheek: [np zeros ((150, 180, 1)), (255, 0, 0), (1, 0, 0)].
}

And How can I set the masks?
Thanks a lot!

**Comment by zhjikoshlizhzc** [comment]
And what does `(150, 180, 1))`mean?
Thanks a lot!

**Comment by edosedgar** [comment]
Hello!

By setting the masks you have to specify the size of the patches in pixels, the color of the grid and decrement value.

Suppose, you have the following grid:

(255, 0, 0), ........, (255, 0, 0)
............................................
(254, 0, 0),.........., (254, 0, 0)

Then you have to set it:
'left_cheek' : [initial values, the start color -> (255, 0, 0), decrement value -> (1, 0, 0)]

Decrement value shows how many you have to subtract from the color to iterate over the grid.
While the algorithm goes over the first line, it looks for the first row of point with **start color**, then
it subtracts the **decrement value** from the **start color**, looks for the second row of points, then subtracts again and so on. Finally, it builds up a grid and transform each quadrangle.
