### ISSUE TITLE
【Novice programmer】version of tensorflow and python

### ISSUE THREAD

**Issue by ghost** [edosedgar/mtcnnattack#5]
Hello！

 I'm a third year college student, and I'm learning about the project of adversarial attack. This is the first project I studied. 

Due to the version problem of tensorflow and python. I have been debugging problems with the version of the software for a long time.

 So would you like to tell me **the version of tensorflow and python** in this project that you use?

**Comment by ghost** [comment]
I got it.

Thank you for your excellent contribution in this project !

**Comment by edosedgar** [comment]
If my memory does not fail me, tf 1.12 and python 3.6
