### ISSUE TITLE
Set mask on my photo

### ISSUE THREAD

**Issue by SURABHI-GUPTA** [edosedgar/mtcnnattack#7]
@edosedgar 

Hello.
I've changed the input photo with my own photo with two checkerboard squares on my face.

The grid_size with your image is (3,3) but with my image its (1,9).

so, I am getting this error 

Traceback (most recent call last):
  File "adversarial_gen.py", line 266, in <module>
    adv_mask.build(sess)
  File "adversarial_gen.py", line 57, in build
    self.pm.compile()
  File "/ssd_scratch/cvit/surabhi/mtcnnattack/utils/patch_mng.py", line 188, in compile
    self.patches[patch_key].init_transforms(self.images)
  File "/ssd_scratch/cvit/surabhi/mtcnnattack/utils/patch_mng.py", line 148, in init_transforms
    xx_dst, yy_dst = image.get_grid(self.init_clr, self.grad_clr, self.grid_size)
  File "/ssd_scratch/cvit/surabhi/mtcnnattack/utils/patch_mng.py", line 62, in get_grid
    xx_dst, yy_dst = self.add_new_line(xx_dst, yy_dst, dots_mask, i)
  File "/ssd_scratch/cvit/surabhi/mtcnnattack/utils/patch_mng.py", line 52, in add_new_line
    xx[i,:], yy[i,:] = points[:,1], points[:,0]
ValueError: could not broadcast input array from shape (20) into shape (9)

**Comment by SURABHI-GUPTA** [comment]
@edosedgar I tried to take photos similar to you (but using mobile camera), but it is not working. Is there any other specific things to focus on ? Please help. 
![1](https://user-images.githubusercontent.com/22388014/101493059-8cc6ac80-398b-11eb-950a-44c076a1b23b.png)

**Comment by edosedgar** [comment]
Did you create the array of points over the checkerboard?

**Comment by edosedgar** [comment]
Refer to this explanation
https://github.com/edosedgar/mtcnnattack/issues/1

And look at the photos given in input_img carefully:
![image](https://user-images.githubusercontent.com/8794648/101493583-8e31ae00-3966-11eb-9943-7d3888833927.png)

**Comment by SURABHI-GUPTA** [comment]
> Did you create the array of points over the checkerboard?

Which array of points? After taking photos with checkerboard, I marked the corners with green and red color and using your code I tried to train on these images.

**Comment by SURABHI-GUPTA** [comment]
> Refer to this explanation
> #1
> 
> And look at the photos given in input_img carefully:
> ![image](https://user-images.githubusercontent.com/8794648/101493583-8e31ae00-3966-11eb-9943-7d3888833927.png)

In this picture, for each corner position marked on checkerboard, is it only pixel changed or neighbouring pixel also ?

**Comment by edosedgar** [comment]
> 
> 
> > Did you create the array of points over the checkerboard?
> 
> Which array of points? After taking photos with checkerboard, I marked the corners with green and red color and using your code I tried to train on these images.

Did you mark all points with the same color or what?

**Comment by edosedgar** [comment]
You have the same color for the whole row, lets say (255, 0, 0), then you go to the second row with (254, 0, 0). On the third row you put (253, 0, 0) for the points. Then you do the same for the right patch but with a different color.

<img width="543" alt="101493583-8e31ae00-3966-11eb-9943-7d3888833927" src="https://user-images.githubusercontent.com/8794648/101613401-01413000-3a0c-11eb-8cbe-0ca6a65c6b13.png">

**Comment by SURABHI-GUPTA** [comment]
@edosedgar thanks for your time and help... issue solved...
