### ISSUE TITLE
Attack failed

### ISSUE THREAD

**Issue by SURABHI-GUPTA** [edosedgar/mtcnnattack#8]
@edosedgar I tried training with 6 images and for 2000, 4000 epochs, but the patch trained seems of no use in detection using MTCNN. Even with trained patches, the detector can detect faces.
![left_cheek](https://user-images.githubusercontent.com/22388014/101772904-09839300-3b12-11eb-8f0c-1115a90d5f3d.png)
![right_cheek](https://user-images.githubusercontent.com/22388014/101772916-0b4d5680-3b12-11eb-94f8-5334d4d3eff7.png)

**Comment by edosedgar** [comment]
That patches do not look ok to me, too frequent texture, you have likely done something wrong, check with the patches given in a repo, they have a different look

**Comment by SURABHI-GUPTA** [comment]
@edosedgar yeah.. I did everything according to your code.. tried for higher epochs, but still not getting good results.

**Comment by edosedgar** [comment]
It looks like you did not implement the resize function, please read the README carefully. It is important that optimization takes place with three downscaled pictures.

**Comment by SURABHI-GUPTA** [comment]
@edosedgar, why I need to change the resize function ?

**Comment by edosedgar** [comment]
Well, since I used the internal Huawei implementation of INTER_AREA resize function (which is supposed to be differentiable), I removed it from the repo.

Refer to this part https://github.com/edosedgar/mtcnnattack/blob/master/utils/inter_area.py

You might try to go with the other resize functions (like simple bi-linear and even nearest neighbors). It should also work. Actually the resize function passes the image further on w/o any resizing now, which is not to going to work.

**Comment by SURABHI-GUPTA** [comment]
@edosedgar If you have removed that from repo, how are results good with your input images ?

**Comment by edosedgar** [comment]
I ran the experiments with the internal implementation I have on my local version of the repo.
Try to use the tf built-in resize function with linear interpolation.

**Comment by aiguoth** [comment]
@edosedgar I try to use the tf built-in resize function : whole = tf.image.resize_images(im_inp, [hs, ws], method=1), but the patchs like this  
![1615277799(1)](https://user-images.githubusercontent.com/12046397/110439928-0c7f2700-80f3-11eb-9073-2712e88fa3e8.png)

when I try to use inter_area I got : LookupError: No gradient defined for operation 'resize_area/resize/ResizeArea' (op type: ResizeArea) it seems not differentiable

**Comment by aiguoth** [comment]
I fixed it by this repo.
https://github.com/Polkach/cv-inter_area-on-tensorflow

**Comment by edosedgar** [comment]
> @edosedgar I try to use the tf built-in resize function : whole = tf.image.resize_images(im_inp, [hs, ws], method=1), but the patchs like this
> when I try to use inter_area I got : LookupError: No gradient defined for operation 'resize_area/resize/ResizeArea' (op type: ResizeArea) it seems not differentiable

Specify a linear interpolation or use the code snippet given above by @Guoth

**Comment by zzyyyyy1020** [comment]
> I fixed it by this repo. https://github.com/Polkach/cv-inter_area-on-tensorflow

Did you succeed in the end?

I put inter_ Replace the area code with the Inter in the link you provide_ Area, no confrontation patch can be generated in the digital domain
