### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by cserezwan** [edosedgar/mtcnnattack#9]
Hello, I'm having the following error in your code:
"AttributeError: module 'tensorflow' has no attribute 'contrib'"
Yes, I know this is because of the TensorFlow older version.
But can you please suggest the following code modification for the TensorFlow 2.3 or latest version?

_**patch_transformed = tf.contrib.image.transform(patch_batched, Mb,
                                                            interpolation="NEAREST",
                                                            name="perspective")**_
                                                            
N.B.: I know that "tf.contrib" has moved out of TF starting TF 2.0 alpha.
Thanks in advance.

**Comment by edosedgar** [comment]
The code was tested only with tf 1.13, forward compatibility is not guaranteed (furthermore, it is likely to be incompatible due to introduced changes).
Moreover, with transforms it is tricky, you have to install tf addons, google it.

**Comment by cserezwan** [comment]
Thanks, I thought if you have a newer version of this code?

**Comment by edosedgar** [comment]
Unfortunately, the code support is discontinued since tf 1.13 is still available.
